### ISSUE TITLE
undefined: stringsutil.SliceTrimSpace

### ISSUE THREAD

**Issue by jamesrwhite** [grokify/swaggman#10]
Hi,

I'm running into the following issue when running `go get github.com/grokify/swaggman` from my project:

```sh
$ go get github.com/grokify/swaggman
# github.com/grokify/swaggman/swagger2
../../../../pkg/mod/github.com/grokify/swaggman@v1.0.0/swagger2/count.go:15:9: undefined: stringsutil.SliceTrimSpace
```

This is a project using Go Modules and Go v1.13.8.

Let me know if I can provide any more info.

**Comment by grokify** [comment]
Thanks for reporting this.

This should be fixed by updating the following packages:

1. `github.com/grokify/swaggman`
1. `github.com/grokify/gotilla`

**Comment by jamesrwhite** [comment]
To get your updates I had to pin to the latest commit with:

```
go get github.com/grokify/swaggman@80df5a79d115c2c5fbe470d3d2c0beaabb3f1e42
```

I think otherwise it uses the [latest release](https://github.com/grokify/swaggman/tree/v1.0.0) which from I can see doesn't have any dependency management so whenever you to try to install it will use the latest versions of any dependencies hence why this issue happened.

It may be worth doing another release as I don't think currently anyone can install this using `go get github.com/grokify/swaggman`?

**Comment by grokify** [comment]
Thanks for the feedback. I've been meaning to spend more time with Go Modules. I've experimented with it but don't understand all the details yet.

**Comment by grokify** [comment]
Go modules is now supported with 25d9c04690c6b988a9ae8ab89331b30d2ed160c0
