### ISSUE TITLE
Build error - specMaster.Tags undefined 

### ISSUE THREAD

**Issue by andrewcretin** [grokify/swaggman#7]
When building  "github.com/grokify/swaggman" on "master" or "v1.0.0" I get the following error.
`
vendor/github.com/grokify/swaggman/openapi3/merge.go:72:32: specMaster.Tags undefined (type *openapi3.Swagger has no field or method Tags)
`
The dependency is included in my Gopkg.toml as follows
`
[[constraint]]
  name = "github.com/grokify/swaggman"
  branch = "master"
`

**Comment by andrewcretin** [comment]
I forked and made some changed in order to get this working for me. Basically, adding Gopkg.toml as a dependency manager makes sure all the necessary versions are included. Feel free to pick any pieces from this PR or disregard entirely - just thought I'd share what I did to get it working. 

Appreciate this library nonetheless!

**Comment by grokify** [comment]
Thanks! This updated back in 983bb29a2041e368d05ca6bdb0611d49eadbd7b3 when `github.com/getkin/kin-openapi/openapi3` moved `Tags` from `Components` to `Swagger`.
